name: Setup & Download

on:
  workflow_call:
    inputs:
      url:
        description: 'jable 影片网址'
        required: false
        type: string
      random:
        description: '随机下载热门影片'
        required: false
        type: string
    outputs:
      fail:
        description: "Check the download is fail"
        value: ${{ jobs.download.outputs.fail }}

jobs:
  setup:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'hcjohn463/JableTVDownload'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
  download:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      fail: ${{ steps.output_error.outputs.fail }}
    steps:
      - name: Run
        run: >
          if [ -n "${{inputs.url}}" ];              
          then python main.py --url ${{inputs.url}} 2> ./err.log;
          elif [ -n "${{inputs.random}}" ]; 
          then python main.py --random True 2> ./err.log;
          else exit 1;
          fi;
      - name: Error
        id: output_error
        if : ${{ failure() && hashFiles('err.log') }}
        run: |
          ERR_MSG=$(cat err.log)
          ERR_MSG="${ERR_MSG//'%'/'%25'}"
          ERR_MSG="${ERR_MSG//$'\n'/'%0A'}"
          ERR_MSG="${ERR_MSG//$'\r'/'%0D'}"
          echo "::error title=err::$ERR_MSG"
          echo "::set-output name=fail::true"