name: '下载 jable 视频'
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'jable 影片网址'
        required: false
      random:
        description: '随机下载热门影片'
        required: false
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'hcjohn463/JableTVDownload'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run
        id: run_python
        run: >
          if [ -n "${{github.event.inputs.url}}" ];              
          then python main.py --url ${{github.event.inputs.url}} 2> ./err.log;
          elif [ -n "${{github.event.inputs.random}}" ]; 
          then python main.py --random True 2> ./err.log;
          else exit 1;
          fi
      - name: Failed
        if: ${{ failure() && hashFiles('err.log')}}
        run: |
          echo "::error title=err::${$(cat err.log)//'\n'/ }"
          if grep -q 'of \"ios\"' err.log;
          then curl --location --request POST 'https://api.github.com/repos/bxb100/jable-action/actions/workflows/16351433/dispatches' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: token ${{ secrets.GH_PAT }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "ref": "main",
              "inputs": {
                  "url": "${{github.event.inputs.url}}",
                  "random":"${{github.event.inputs.random}}"
              }
          }'
          fi
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: jable
          files: ./**\-**/**
