name: '下载 jable 视频'
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'jable 影片网址'
        required: false
      random:
        description: '随机下载热门影片'
        required: false
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'hcjohn463/JableTVDownload'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run
        id: run_python
        run: >
          if [ -n "${{github.event.inputs.url}}" ];              
          then python main.py --url ${{github.event.inputs.url}};
          elif [ -n "${{github.event.inputs.random}}" ]; 
          then python main.py --random True;
          else exit 1;
          fi
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: ./**\-**/**
