name: 'N_m3u8DL-CLI 上传 release action'
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'jable 影片网址'
        required: false
jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Check input
        if: ${{ github.event.inputs.url == '' }}
        run: |
          echo '::error title=⛔️ ERROR::请输入链接'
      - id: cx
        name: Download
        run: |
          echo "::set-output name=date::$(get-date -format 'yyyy-MM-dd')"
          $uri = '${{ github.event.inputs.url }}'
          iwr -Uri "https://raw.githubusercontent.com/bxb100/OSS-Script/main/Win/execute.ps1" | iex
        shell: pwsh
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.cx.outputs.date}}
          files: '*.mp4'
