name: 'KKK 下载并上传到 Release 中'

on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'jable 影片网址'
        required: false
      random:
        description: '随机下载热门影片'
        required: false
  
jobs:
  job1:
    uses: bxb100/jable-action/.github/workflows/download.yml@main
    with:
      url: ${{ github.event.inputs.url }}
      random: ${{ github.event.inputs.random }}

  retry:
    needs: job1
    uses: bxb100/jable-action/.github/workflows/retry.yml@main
    with: 
      url: ${{ github.event.inputs.url }}
      random: ${{ github.event.inputs.random }}
      fail: ${{ needs.job1.outputs.fail }}
      workflow_id: 11111

  release:
    needs: retry
    uses: bxb100/jable-action/.github/workflows/release.yml@main
