name: Retry

on:
  workflow_call:
    inputs:
      url:
        description: 'jable 影片网址'
        required: false
        type: string
      random:
        description: '随机下载热门影片'
        required: false
        type: string
      fail:
        required: false
        default: false
        type: boolean
      workflow_id:
        description: "重新调用 workflow 的 id"
        required: true
        type: string

jobs:
  retry:
    name: check fail and recall the workflow
    runs-on: ubuntu-latest
    if: ${{ inputs.fail }}
    steps:
      - name: Retry
        shell: sh
        run: |
          if grep -q 'of \"ios\"' err.log;
          then curl --location --request POST 'https://api.github.com/repos/bxb100/jable-action/actions/workflows/${{inputs.workflow_id}}/dispatches' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: token ${{ secrets.GH_PAT }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "ref": "main",
              "inputs": {
                  "url": "${{ inputs.url }}",
                  "random":"${{ inputs.random }}"
              }
          }'
          fi