name: '测试 WebDAV 连接'
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir add-dd &&
          echo 'OMG' > ./add-dd/test.txt
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Publish
        uses: bxb100/action-upload-webdav@main
        with:
          webdav_address: "http://100.90.96.54:5000"
          webdav_username: ${{secrets.username}}
          webdav_password: ${{secrets.password}}
          webdav_upload_path: "/Video/AV"
          files: ./**\-**/**
